sudo: required
language: go
go:
    - tip
    
notifications:
    email: false

services:
  - docker
  
before_install:
- docker pull apcera/gnatsd
- docker run -d -p 4222:4222 -p 8333:8333 apcera/gnatsd
- docker pull mongo
- docker run -d -p 27017:27017 mongo
- docker ps -a

install:
  - go get github.com/nats-io/nats
  - go get github.com/suricatatalk/guardian/auth
  - go get golang.org/x/crypto/bcrypt
  - go get gopkg.in/mgo.v2
  - go get gopkg.in/mgo.v2/bson
  - go get github.com/satori/go.uuid
  - go get github.com/Sirupsen/logrus
  - go get github.com/sohlich/nats-proxy
  - go get github.com/sebest/logrusly
  - go get github.com/suricatatalk/gate/jwt
  - go get github.com/suricatatalk/gate/storage
  - go get github.com/suricatatalk/guardian/auth
  - go get github.com/suricatatalk/mail/client
  - go get github.com/kelseyhightower/envconfig